version: 1-alpha.1

releases:
  vega-shell-testing:
    name: VEGA Shell
    autodeploy-on: default
    chart: csssr/static-site@~1.0.0
    static-params:
      projectID: vega
    builds:
      - workflow: build-static.yaml
        values:
          buildID: build-{{ .Build.RunID }}
